[profile.default]
names = true
sizes = true
src = "src"
test = "test/forge"
fs_permissions = [
    { access = "read", path = "./config/"},
    { access = "read", path = "./lib/morpho-blue/out/"},
    { access = "read", path = "./lib/universal-rewards-distributor/out/"},
]
evm_version = "cancun"
libs = ["lib"]

[profile.default.fuzz]
runs = 16


[profile.default.rpc_endpoints]
ethereum = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
tenderly = "https://rpc.tenderly.co/fork/${TENDERLY_FORK_ID}"

[profile.default.fmt]
wrap_comments = true


[profile.build]
via-ir = true
test = "/dev/null"
script = "/dev/null"
optimizer_runs = 80000


[profile.test]
via-ir = false


# See more config options https://github.com/foundry-rs/foundry/tree/master/crates/config
